### ISSUE TITLE
k-Means reverse-windowing results with dimensions mismatch

### ISSUE THREAD

**Issue by Kotrix** [HPI-Information-Systems/TimeEval-algorithms#8]
@wenig It is impossible to evaluate k-Means because the _custom_reverse_windowing() causes a dimension mismatch between y_true and y_score. Error logs below. 

```
Starting evaluation of experiment k-Means-NASA-MSL-M-4-d751713988987e9331980363e24189ce-1

Performing execution for UNSUPERVISED algorithm k-Means
Running container 'registry.gitlab.hpi.de/akita/i/kmeans:latest' with uid=1000 and gid=1000 privileges in ExecutionType.EXECUTE mode.
Restricting container to 8.0 CPUs and 11.362 GB RAM

#### Docker container logs ####
/usr/local/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py:793: FutureWarning: 'n_jobs' was deprecated in version 0.23 and will be removed in 1.0 (renaming of 0.25).
  " removed in 1.0 (renaming of 0.25).", FutureWarning)
Required padding_length=0
Reversing window-based scores to point-based scores:
Before reverse-windowing: scores.shape=(2019,)
After reverse-windowing: scores.shape=(2038,)

###############################

Scoring algorithm k-Means with ROC_AUC metrics
Calculating Metric.ROC_AUC
Exception while computing metric Metric.ROC_AUC: boolean index did not match indexed array along dimension 0; dimension is 2038 but corresponding boolean dimension is 2057


2022-10-26 13:51:13,480  ERROR -             TimeEval: Exception occurred during the evaluation of k-Means on the dataset Dataset(datasetId=('NASA-MSL', 'M-4'), dataset_type='real', training_type=<TrainingType.SEMI_SUPERVISED: 'semi-supervised'>, length=2038, dimensions=1, contamination=0.123159961, min_anomaly_length=251, median_anomaly_length=251, max_anomaly_length=251, period_size=6.0, num_anomalies=1).
Traceback (most recent call last):
  File "/home/kotrix/anaconda3/envs/timeeval/lib/python3.8/site-packages/timeeval/timeeval.py", line 175, in _run
    result = exp.evaluate()
  File "/home/kotrix/anaconda3/envs/timeeval/lib/python3.8/site-packages/timeeval/experiments.py", line 129, in evaluate
    raise last_exception
  File "/home/kotrix/anaconda3/envs/timeeval/lib/python3.8/site-packages/timeeval/experiments.py", line 113, in evaluate
    score = metric(y_true, y_scores)
  File "/home/kotrix/anaconda3/envs/timeeval/lib/python3.8/site-packages/timeeval/utils/metrics.py", line 80, in __call__
    y_true, y_score = self._validate_scores(y_true, y_score, **kwargs)
  File "/home/kotrix/anaconda3/envs/timeeval/lib/python3.8/site-packages/timeeval/utils/metrics.py", line 74, in _validate_scores
    y_score[penalize_mask] = (~np.array(y_true[penalize_mask], dtype=bool)).astype(np.int_)
IndexError: boolean index did not match indexed array along dimension 0; dimension is 2038 but corresponding boolean dimension is 2057
```

**Comment by CodeLionX** [comment]
The shape `(2038, )` after reverse windowing is the correct shape for the scores because the dataset NASA-MSL / M-4 has exactly 2038 points:
![image](https://user-images.githubusercontent.com/10573700/198027391-54fed554-2988-4f8e-82f2-8254509f75e2.png)

It seems like you have an additional step in the postprocessing function of your k-Means `Algorithm`-definition. I can't reproduce the issue with the following experiment configuration (based on TimeEval-`main`-branch):

```python
#!/usr/bin/env python3

from pathlib import Path
from timeeval import TimeEval, DatasetManager, DefaultMetrics, Algorithm, TrainingType, InputDimensionality
from timeeval.adapters import DockerAdapter

def main():
    dm = DatasetManager(Path("../data/benchmark-data/data-processed"))  # or test-cases directory
    datasets = dm.select(collection="NASA-MSL", dataset="M-4")

    algorithms = [Algorithm(
        name="k-Means",
        main=DockerAdapter(
            image_name="registry.gitlab.hpi.de/akita/i/kmeans",
            skip_pull=True,
            group_privileges="akita",
        ),
        data_as_file=True,
        training_type=TrainingType.UNSUPERVISED,
        input_dimensionality=InputDimensionality("multivariate")
    )]

    timeeval = TimeEval(dm, datasets, algorithms, metrics=[DefaultMetrics.ROC_AUC, DefaultMetrics.RANGE_PR_AUC])

    timeeval.run()
    results = timeeval.get_results(aggregated=False)
    print(results)


if __name__ == "__main__":
    main()
```

Output:

```
Running PREPARE phase
Running EVALUATION phase
Evaluating: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.09s/it]
Running FINALIZE phase
FINALIZE phase done.
          Stored results at <some-folder>/results/2022_10_26_14_54_36/results.csv.
          Overall runtime of this TimeEval run: 4.114354848861694 seconds
        
  algorithm collection dataset algo_training_type algo_input_dimensionality dataset_training_type dataset_input_dimensionality  ...     status  error_message  repetition  hyper_params                   hyper_params_id   ROC_AUC  RANGE_PR_AUC
0   k-Means   NASA-MSL     M-4       UNSUPERVISED              MULTIVARIATE       SEMI_SUPERVISED                   UNIVARIATE  ...  Status.OK            NaN           1            {}  d751713988987e9331980363e24189ce  0.543491      0.132834

[1 rows x 19 columns]
```

**Comment by Kotrix** [comment]
> I found out that our algorithm stubs in timeeval_experiments were outdated: https://github.com/HPI-Information-Systems/TimeEval/pull/39. Maybe this was the source of your error; should be fixed after the PR is merged.

Yes, this was exactly the case. It works now. Thanks!
